#set($hash = '#')
${hash} The following properties are required for (productive) ${projectName} deployment.
${hash} For productive deployment, all properties must be configured or enabled.
${hash} Only relevant properties should be listed here; otherwise, they should be deleted.
${hash} Unless otherwise specified, empty properties are relevant and must be configured.
${hash} Temporary disabled properties require further configuration or other dependencies.

${hash.repeat(78)}
${hash} Basic                                                                      ${hash}
${hash.repeat(78)}
${hash} Configure base url, e.g. http://domain:port, without '/'. Temporary disabled to use default.
${hash}MCR.baseurl=
${hash} Requires MCR.baseurl, therefore temporary disabled.
${hash}MIR.CanonicalBaseURL=%MCR.baseurl%/
MCR.NameOfProject=${projectName}
MCR.Metadata.Languages=de

${hash.repeat(78)}
${hash} Editor                                                                     ${hash}
${hash.repeat(78)}
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed

${hash.repeat(78)}
${hash} Frontend                                                                   ${hash}
${hash.repeat(78)}
MIR.CustomLayout.JS=${projectName}.js
