#set($hash = '#')
${hash} The following properties are required for (productive) ${projectName} deployment.
${hash} For productive deployment, all properties must be configured or enabled.
${hash} Only relevant properties should be listed here; otherwise, they should be deleted.
${hash} Unless otherwise specified, empty properties are relevant and must be configured.
${hash} Temporary disabled properties require further configuration or other dependencies.

${hash.repeat(78)}
${hash} Basic                                                                      ${hash}
${hash.repeat(78)}
${hash} Configure base url, e.g. http://domain:port, without '/'. Temporary disabled to use default.
${hash}MCR.baseurl=
${hash} Requires MCR.baseurl, therefore temporary disabled.
${hash}MIR.CanonicalBaseURL=%MCR.baseurl%/
MCR.NameOfProject=${projectName}
MCR.Metadata.Languages=de,en

${hash.repeat(78)}
${hash} OAI                                                                        ${hash}
${hash.repeat(78)}
MCR.Mail.Server=
# General sender mail address, e.g. mail@domain
MCR.Mail.Sender=

# Mail for events including self registration, e.g. <name> mail@domain
MCR.mir-module.EditorMail=
# Sender email for events, e.g. <name> mail@domain
MCR.mir-module.MailSender=

${hash.repeat(78)}
${hash} OAI                                                                        ${hash}
${hash.repeat(78)}
MCR.DOI.Prefix=
MCR.DOI.HostingInstitution=

# Configuration is required, therefore service temporary disabled.
#MCR.PI.Service.Datacite=org.mycore.pi.doi.MCRDOIService
MCR.PI.Service.Datacite.MetadataService=MODSDOI
MCR.PI.Service.Datacite.RegisterBaseURL=%MCR.baseurl%
MCR.PI.Service.Datacite.Username=
MCR.PI.Service.Datacite.Password=
MCR.PI.Service.Datacite.RegisterURLContext=receive/$ID
MCR.PI.Service.Datacite.RegistrationPredicate=org.mycore.pi.condition.MCRPIPublishedPredicate
MCR.PI.Service.Datacite.Transformer=datacite
MCR.PI.Service.Datacite.Generator=

MCR.PI.MetadataService.MODSDOI=org.mycore.mods.identifier.MCRMODSDOIMetadataService
MCR.PI.MetadataService.MODSDOI.Prefix=%MCR.DOI.Prefix%

${hash.repeat(78)}
${hash} OAI                                                                        ${hash}
${hash.repeat(78)}
MCR.OAIDataProvider.OAI2.RepositoryName=
MCR.OAIDataProvider.OAI2.RepositoryIdentifier=
MCR.OAIDataProvider.OAI2.AdminEmail=
MCR.OAIDataProvider.OAI2.RecordSampleID=
MCR.OAIDataProvider.OAI2.DescriptionURI.EPrints=webapp:oai/oai-eprints.xml
MCR.OAIDataProvider.OAI2.DescriptionURI.Rights=webapp:oai/oai-rights.xml

${hash.repeat(78)}
${hash} ePuSta                                                                     ${hash}
${hash.repeat(78)}
# ePuSta endpoint is required, therefore temporarily disabled.
#MIR.ePuSta=show
MIR.ePuSta.providerURL=

${hash.repeat(78)}
${hash} Workflow                                                                   ${hash}
${hash.repeat(78)}
MIR.Workflow.Menu=true
MIR.Workflow.Box=true

${hash.repeat(78)}
${hash} Editor                                                                     ${hash}
${hash.repeat(78)}
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed

${hash.repeat(78)}
${hash} Frontend                                                                   ${hash}
${hash.repeat(78)}
MIR.CustomLayout.JS=${projectName}.js

${hash.repeat(78)}
${hash} Disable Servlets                                                           ${hash}
${hash.repeat(78)}
MCR.Servlet.MirSelfRegistrationServlet.Disabled=true
